routing para los archivos y agrego html y css
yollotltamayo/webmac pull request #6
Opened 2021-03-19 23:53 UTC by yollotltamayo

Routing par poder cargar archivos desde html

2021-03-21 05:03 UTC, mucinoab requested changes
Andas reinventando la rueda bro, checha [aquí.](https://api.rocket.rs/master/rocket_contrib/serve/struct.StaticFiles.html)

2021-03-23 01:57 UTC, dianapg8 commented
ya cheque [https://api.rocket.rs/master/rocket_contrib/serve/struct.StaticFiles.html](esto) y no se que cambios deberia haber, @mucinoab ??

2021-03-23 02:06 UTC, mucinoab commented
Las funciones que implementó tiene la misma funcionalidad que lo que mandé, sería usar lo que ponen en el ejemplo. @yollotltamayo @dianapg8

2021-03-23 02:08 UTC, dianapg8 commented
o sea implementar lo de .rank() ?

2021-03-23 02:14 UTC, mucinoab commented
Todo esto 
```rust
use rocket::response::NamedFile;
use rocket_contrib::serve::StaticFiles;
use std::path::{Path, PathBuf};

fn index() -> Option<NamedFile> {
    NamedFile::open("static/index.html").ok()
}
#[get("/<file..>")]
fn files(file:PathBuf)->Option<NamedFile> {
    NamedFile::open(Path::new("static").join(file)).ok()
}
```

Puede ser solo esto:

```rust
use rocket_contrib::serve::StaticFiles;

#[launch]
fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/public", StaticFiles::from("/static"))
}
```

2021-03-23 02:16 UTC, dianapg8 commented
:0
thx

2021-04-06 02:42 UTC, closed without merging